Merge hq-compose-services.yml into hq-compose.yml

diff --git a/docker/hq-compose.yml b/docker/hq-compose.yml
--- a/docker/hq-compose.yml
+++ b/docker/hq-compose.yml
@@ -1,50 +1,5 @@
 version: '2.3'
 services:
-  web:
-    build:
-      context: .
-      dockerfile: "${DOCKERFILE}"
-    environment:
-      CI: "${CI}"
-      CODECOV_TOKEN: "${CODECOV_TOKEN}"
-      DATADOG_API_KEY: "${DATADOG_API_KEY}"
-      DATADOG_APP_KEY: "${DATADOG_APP_KEY}"
-      DEPENDENT_SERVICES: "couch:5984 postgres:5432 redis:6379 elasticsearch2:9200 minio:9980 kafka:9092"
-      DOCKER_HQ_OVERLAY: "${DOCKER_HQ_OVERLAY}"
-      DOCKER_HQ_OVERLAYFS_CHMOD: "${DOCKER_HQ_OVERLAYFS_CHMOD}"
-      DOCKER_HQ_OVERLAYFS_METACOPY: "${DOCKER_HQ_OVERLAYFS_METACOPY}"
-      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
-      GITHUB_EVENT_NAME: "${GITHUB_EVENT_NAME}"
-      JS_SETUP: "${JS_SETUP}"
-      JS_TEST_EXTENSIONS: "${JS_TEST_EXTENSIONS}"
-      NOSE_DIVIDED_WE_RUN: "${NOSE_DIVIDED_WE_RUN}"
-      REUSE_DB: "${REUSE_DB}"
-      TRAVIS: "${TRAVIS}"
-      TRAVIS_BRANCH: "${TRAVIS_BRANCH}"
-      TRAVIS_BUILD_ID: "${TRAVIS_BUILD_ID}"
-      TRAVIS_BUILD_NUMBER: "${TRAVIS_BUILD_NUMBER}"
-      TRAVIS_COMMIT: "${TRAVIS_COMMIT}"
-      TRAVIS_EVENT_TYPE: "${TRAVIS_EVENT_TYPE}"
-      TRAVIS_JOB_ID: "${TRAVIS_JOB_ID}"
-      TRAVIS_JOB_NUMBER: "${TRAVIS_JOB_NUMBER}"
-      TRAVIS_PULL_REQUEST: "${TRAVIS_PULL_REQUEST}"
-      TRAVIS_PULL_REQUEST_BRANCH: "${TRAVIS_PULL_REQUEST_BRANCH}"
-      TRAVIS_PULL_REQUEST_SHA: "${TRAVIS_PULL_REQUEST_SHA}"
-      TRAVIS_REPO_SLUG: "${TRAVIS_REPO_SLUG}"
-    privileged: true  # allows mount inside container
-    links:
-      - postgres
-      - couch
-      - redis
-      - elasticsearch2
-      - elasticsearch5
-      - kafka
-      - zookeeper
-      - minio
-    volumes:
-      - ..:/mnt/commcare-hq-ro${RO}
-      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-lib:}/mnt/lib
-
   formplayer:
     image: dimagi/formplayer
     environment:
@@ -52,9 +7,12 @@ services:
       COMMCARE_ALTERNATE_ORIGINS: "http://localhost:8000,http://127.0.0.1:8000"
       AUTH_KEY: "secretkey"
       EXTERNAL_REQUEST_MODE: "replace-host"
-    expose:
-      - "8080"
-      - "8081"
+    depends_on:
+      - postgres
+      - redis
+    ports:
+      - "8080:8080"
+      - "8081:8081"
 
   postgres:
     extends:
@@ -63,8 +21,8 @@ services:
     environment:
       POSTGRES_USER: commcarehq
       POSTGRES_PASSWORD: commcarehq
-    expose:
-      - "5432"
+    ports:
+      - "5432:5432"
     volumes:
       - ${VOLUME_PREFIX}${BLANK_IF_TESTS-postgresql:}/var/lib/postgresql/data
 
@@ -77,34 +35,38 @@ services:
       nofile:
         soft: 1024
         hard: 1048576
-    expose:
-      - "5984"
+    ports:
+      - "5984:5984"
     volumes:
       - ${VOLUME_PREFIX}${BLANK_IF_TESTS-couchdb2:}/usr/src/couchdb/dev/lib/node1/data
 
   redis:
     image: redis
-    expose:
-      - "6379"
+    ports:
+      - "6379:6379"
     volumes:
       - ${VOLUME_PREFIX}${BLANK_IF_TESTS-redis:}/data
 
   elasticsearch2:
     image: elasticsearch:2.4.6
+    command: elasticsearch --cluster.name=${ES_CLUSTER_NAME}
     environment:
+      ES_CLUSTER_NAME: ${ES_CLUSTER_NAME}
       ES_JAVA_OPTS: "-Des.script.engine.groovy.inline.aggs=true -Des.script.engine.groovy.inline.search=true"
-    expose:
-      - "9200"
+    ports:
+      - "9200:9200"
     volumes:
       - ${VOLUME_PREFIX}${BLANK_IF_TESTS-elasticsearch2:}/usr/share/elasticsearch/data
       - ./files/elasticsearch_2.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
 
   elasticsearch5:
     image: elasticsearch:5.6.16
+    command: elasticsearch
     environment:
+      ES_CLUSTER_NAME: ${ES_CLUSTER_NAME}
       ES_JAVA_OPTS: "-Xms750m -Xmx750m -Des.script.engine.groovy.inline.aggs=true -Des.script.engine.groovy.inline.search=true"
-    expose:
-      - "9200"
+    ports:
+      - "9205:9200"
     volumes:
       - ${VOLUME_PREFIX}${BLANK_IF_TESTS-elasticsearch5:}/usr/share/elasticsearch/data
       - ./files/elasticsearch_5.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
@@ -117,31 +79,31 @@ services:
       - ${VOLUME_PREFIX}${BLANK_IF_TESTS-zookeeper:}/opt/zookeeper-3.4.13/data
 
   kafka:
-      image: wurstmeister/kafka:2.13-2.6.0
-      ports:
-        - "9092:9092"
-      environment:
-          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
-          KAFKA_BROKER_ID: 1
-          KAFKA_ADVERTISED_PORT: 9092
-          CUSTOM_INIT_SCRIPT: |
-            URL="https://raw.githubusercontent.com/vishnubob/wait-for-it/c096cface5fbd9f2d6b037391dfecae6fde1362e/wait-for-it.sh"
-            if curl --max-time 10 $URL > wait.sh ; then
-              chmod +x ./wait.sh
-              ./wait.sh -t 30 zookeeper:2181 || exit 1
-            else
-              echo "Wait script download failed"
-            fi
-          KAFKA_ADVERTISED_HOST_NAME: "kafka"
-      volumes:
-        - ${DOCKER_SOCK:-/var/run/docker.sock}:${DOCKER_SOCK:-/var/run/docker.sock}
-        - ${VOLUME_PREFIX}${BLANK_IF_TESTS-kafka:}/kafka/kafka-logs-1
+    image: wurstmeister/kafka:2.13-2.6.0
+    ports:
+      - "9092:9092"
+    environment:
+      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
+      KAFKA_BROKER_ID: 1
+      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME:-kafka}
+      KAFKA_ADVERTISED_PORT: 9092
+      CUSTOM_INIT_SCRIPT: |
+        URL="https://raw.githubusercontent.com/vishnubob/wait-for-it/c096cface5fbd9f2d6b037391dfecae6fde1362e/wait-for-it.sh"
+        if curl --max-time 10 \$URL > wait.sh ; then
+          chmod +x ./wait.sh
+          ./wait.sh -t 30 zookeeper:2181 || exit 1
+        else
+          echo "Wait script download failed"
+        fi
+    volumes:
+      - ${DOCKER_SOCK:-/var/run/docker.sock}:${DOCKER_SOCK:-/var/run/docker.sock}
+      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-kafka:}/kafka/kafka-logs-1
 
   minio:
     image: minio/minio
     command: server --address :9980 /data
-    expose:
-      - "9980"
+    ports:
+      - "9980:9980"
     volumes:
       - ${VOLUME_PREFIX}${BLANK_IF_TESTS-minio-conf:}/root/.minio
       - ${VOLUME_PREFIX}${BLANK_IF_TESTS-minio-data:}/data
