Do not exit kafaka-startup.sh if download fails
Misunderstood how this worked. See
https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L146

diff --git a/docker/hq-compose.yml b/docker/hq-compose.yml
--- a/docker/hq-compose.yml
+++ b/docker/hq-compose.yml
@@ -125,11 +125,14 @@ services:
           KAFKA_BROKER_ID: 1
           KAFKA_ADVERTISED_PORT: 9092
           CUSTOM_INIT_SCRIPT: |
-            set -e
             URL="https://raw.githubusercontent.com/vishnubob/wait-for-it/c096cface5fbd9f2d6b037391dfecae6fde1362e/wait-for-it.sh"
-            curl $URL > wait.sh || exit 0  # skip wait if script download fails
-            chmod +x ./wait.sh
-            ./wait.sh -t 30 zookeeper:2181
+            curl $URL > wait.sh
+            if [ -f wait.sh ]; then
+              chmod +x ./wait.sh
+              ./wait.sh -t 30 zookeeper:2181 || exit 1
+            else
+              echo "Wait script download failed"
+            fi
           KAFKA_ADVERTISED_HOST_NAME: "kafka"
       volumes:
         - /var/run/docker.sock:/var/run/docker.sock
